### ISSUE TITLE
Is it working in 2024?

### ISSUE THREAD

**Issue by alaminkouser** [klich3/firebase-gpt-chat-completion-stream#1]
Used the same code and got this error.

This is my log:

```2024-02-29T21:56:50.449235Z ? gptPromptStream:     at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
2024-02-29T21:56:50.449242Z ? gptPromptStream:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-29T21:56:50.461221900Z D gptPromptStream: Function execution took 64 ms, finished with status: 'crash'
2024-02-29T21:57:31.220523375Z D gptPromptStream: Function execution started
2024-02-29T21:57:31.294477Z E gptPromptStream: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
2024-02-29T21:57:31.294489Z ? gptPromptStream:     at /workspace/index.js:21:26
2024-02-29T21:57:31.294497Z ? gptPromptStream:     at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)
2024-02-29T21:57:31.294504Z ? gptPromptStream:     at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
2024-02-29T21:57:31.294510Z ? gptPromptStream:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-29T21:57:31.295781815Z D gptPromptStream: Function execution took 75 ms, finished with status: 'crash'
2024-02-29T21:57:35.357779095Z D gptPromptStream: Function execution started
2024-02-29T21:57:35.361857Z E gptPromptStream: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
2024-02-29T21:57:35.361868Z ? gptPromptStream:     at /workspace/index.js:21:26
2024-02-29T21:57:35.361875Z ? gptPromptStream:     at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)
2024-02-29T21:57:35.361882Z ? gptPromptStream:     at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
2024-02-29T21:57:35.361887Z ? gptPromptStream:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-29T21:57:35.363138113Z D gptPromptStream: Function execution took 5 ms, finished with status: 'crash'
2024-02-29T21:57:37.293975747Z D gptPromptStream: Function execution started
2024-02-29T21:57:37.297647Z E gptPromptStream: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
2024-02-29T21:57:37.297659Z ? gptPromptStream:     at /workspace/index.js:21:26
2024-02-29T21:57:37.297667Z ? gptPromptStream:     at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)
2024-02-29T21:57:37.297673Z ? gptPromptStream:     at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
2024-02-29T21:57:37.297678Z ? gptPromptStream:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-29T21:57:37.298594712Z D gptPromptStream: Function execution took 4 ms, finished with status: 'crash'
2024-02-29T21:58:19.483189427Z D gptPromptStream: Function execution started
2024-02-29T21:58:19.488550Z E gptPromptStream: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
2024-02-29T21:58:19.488573Z ? gptPromptStream:     at /workspace/index.js:21:26
2024-02-29T21:58:19.488581Z ? gptPromptStream:     at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)
2024-02-29T21:58:19.488587Z ? gptPromptStream:     at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
2024-02-29T21:58:19.488592Z ? gptPromptStream:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-29T21:58:19.489984676Z D gptPromptStream: Function execution took 6 ms, finished with status: 'crash'
2024-02-29T22:00:21.119884905Z D gptPromptStream: Function execution started
2024-02-29T22:00:22.547396Z E gptPromptStream: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:794:10)
    at ServerResponse.json (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:275:10)
    at ServerResponse.send (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:162:21)
    at /workspace/index.js:85:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-02-29T22:01:04.201310994Z D gptPromptStream: Function execution started
2024-02-29T22:01:05.719887Z E gptPromptStream: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:794:10)
    at ServerResponse.json (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:275:10)
    at ServerResponse.send (/layers/google.nodejs.functions-framework/functions-framework/node_modules/express/lib/response.js:162:21)
    at /workspace/index.js:85:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by klich3** [comment]
probably not, because langchain is updated every day, so you can adapt the part of the code to a new one.

**Comment by alaminkouser** [comment]
Please add a notice in README.md. Other people may spend hours on it trying to fix.

**Comment by klich3** [comment]
Of course thanks
